CREATE DATABASE STUFF_DB;
CREATE TABLE STUFF_DETAILS
(
ID INT PRIMARY KEY,
NAME VARCHAR(50),
MOBILE INT,
SALARY INT,
PICTURE IMAGE
);
SELECT * FROM STUFF_DETAILS;

DELETE FROM STUFF_DETAILS WHERE ID='101';

CREATE TABLE SELLER_DETAILS
(
SELLER_NAME VARCHAR(50),
NUMBER VARCHAR(50),
LOCATION VARCHAR(50),
ANIMAL_TYPE VARCHAR(50),
ANIMAL_QUANTITY VARCHAR(50)
);

SELECT * FROM SELLER_DETAILS;

DELETE FROM SELLER_DETAILS WHERE NUMBER='01787656789';