CREATE DATABASE CUSTOMER_DB;
CREATE TABLE CUSTOMER_DETAILS
(
NAME VARCHAR(50),
MOBILE INT PRIMARY KEY,
ADDRESS_ VARCHAR(50),
AMOUNT INT,
DATE_ VARCHAR(50),
USER__NAME VARCHAR(50),
PASS VARCHAR(50),
PICTURE IMAGE

);
DELETE FROM CUSTOMER_DETAILS WHERE MOBILE='1765532849';

CREATE TABLE CUSTOMER_COMMENTS
(
COMMENT VARCHAR(50)
);

SELECT * FROM CUSTOMER_DETAILS;
SELECT * FROM CUSTOMER_COMMENTS;

SELECT NAME, AMOUNT
FROM CUSTOMER_DETAILS;

SELECT SUM(AMOUNT) AS TOTAL_AMOUNT FROM CUSTOMER_DETAILS;

CREATE TABLE ADD_SLOT
(
S_NUMBER INT PRIMARY KEY,
S_SIZE VARCHAR(50),
COW_CAPACITY VARCHAR(50),
SLOT_PRICE INT,
SLOT_LOCATION VARCHAR(50),
PICTURE IMAGE

);

SELECT * FROM ADD_SLOT;


CREATE TABLE CARD_SLOT
(
S_NUMBER INT PRIMARY KEY,
S_SIZE VARCHAR(50),
COW_CAPACITY VARCHAR(50),
SLOT_PRICE INT,
SLOT_LOCATION VARCHAR(50),
PICTURE IMAGE,
SELL_NAME VARCHAR(50)

);

SELECT * FROM CARD_SLOT;
DELETE FROM CARD_SLOT WHERE S_NUMBER='1';